// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ugoimceidzwjytznhwig.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVnb2ltY2VpZHp3anl0em5od2lnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1ODU5MzIsImV4cCI6MjA3NzE2MTkzMn0.6z0tM30AFrFuhzn1-xHgbfDKHEOTYJNnipC6bUoedLU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});